In [1]:
from data_collector import *
import pandas as pd
from config import GOOGLE_MAPS_DATASETS
pd.set_option("display.max.columns", None)

# Finding Aggregated Places in CPH Bounding box

As as 'sanity check', we use Aggregated Places to compare the result to the Quadtree implementation.

In [2]:
COPENHAGEN_BOUNDS = {
    "lat_south": 55.51,
    "lat_north": 55.82,
    "lon_west": 12.23,
    "lon_east": 12.73,
}

response = find_aggregated_places(COPENHAGEN_BOUNDS) 
cph_df = pd.read_json(GOOGLE_MAPS_DATASETS / "copenhagen-bounds-limit10_20260316_125502.json")

print(f"Shape of Quadtree implementation: {cph_df.shape}")
print(f"Response from Places Aggregated with same BB: {response}")

Shape of Quadtree implementation: (4392, 66)
Response from Places Aggregated with same BB: {'error': {'code': 403, 'message': 'This API method requires billing to be enabled. Please enable billing on project #357676775000 by visiting https://console.developers.google.com/billing/enable?project=357676775000 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.', 'status': 'PERMISSION_DENIED', 'details': [{'@type': 'type.googleapis.com/google.rpc.ErrorInfo', 'reason': 'BILLING_DISABLED', 'domain': 'googleapis.com', 'metadata': {'consoleUrl': 'https://console.developers.google.com/billing/enable?project=357676775000', 'service': 'areainsights.googleapis.com', 'containerInfo': '357676775000', 'consumer': 'projects/357676775000'}}, {'@type': 'type.googleapis.com/google.rpc.LocalizedMessage', 'locale': 'en-US', 'message': 'This API method requires billing to be enabled. Please enable billing on project #357676775000 by visiting https://console.developers.google.com/billing/enable?project=357676775000 then retry. If you enabled billing for this project recently, wait a few minutes for the action to propagate to our systems and retry.'}, {'@type': 'type.googleapis.com/google.rpc.Help', 'links': [{'description': 'Google developers console billing', 'url': 'https://console.developers.google.com/billing/enable?project=357676775000'}]}]}}

# Exploring the Copenhagen Data

In [3]:
cph_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4392 entries, 0 to 4391
Data columns (total 66 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          4392 non-null   str
 1   id                            4392 non-null   str
 2   types                         4392 non-null   object
 3   nationalPhoneNumber           3758 non-null   str
 4   internationalPhoneNumber      3758 non-null   str
 5   formattedAddress              4392 non-null   str
 6   addressComponents             4392 non-null   object
 7   plusCode                      4381 non-null   object
 8   location                      4392 non-null   object
 9   viewport                      4392 non-null   object
 10  rating                        4046 non-null   float64
 11  googleMapsUri                 4392 non-null   str
 12  websiteUri                    3600 non-null   str
 13  regularOpeningHours           3805 non-null   object
 14  utcOffsetMinutes              4392 non-null   int64
 15  adrFormatAddress              4392 non-null   str
 16  businessStatus                4392 non-null   str
 17  priceLevel                    1738 non-null   str
 18  userRatingCount               4046 non-null   float64
 19  iconMaskBaseUri               4392 non-null   str
 20  iconBackgroundColor           4392 non-null   str
 21  displayName                   4392 non-null   object
 22  primaryTypeDisplayName        4387 non-null   object
 23  takeout                       3237 non-null   float64
 24  delivery                      2968 non-null   float64
 25  dineIn                        3910 non-null   float64
 26  reservable                    2367 non-null   float64
 27  servesBreakfast               1732 non-null   float64
 28  servesLunch                   3009 non-null   float64
 29  servesDinner                  3249 non-null   float64
 30  servesBeer                    2754 non-null   float64
 31  servesWine                    2451 non-null   float64
 32  servesBrunch                  1713 non-null   float64
 33  currentOpeningHours           3805 non-null   object
 34  currentSecondaryOpeningHours  543 non-null    object
 35  regularSecondaryOpeningHours  543 non-null    object
 36  primaryType                   4387 non-null   str
 37  shortFormattedAddress         4392 non-null   str
 38  reviews                       4046 non-null   object
 39  photos                        3966 non-null   object
 40  outdoorSeating                2187 non-null   float64
 41  liveMusic                     3465 non-null   float64
 42  menuForChildren               2044 non-null   float64
 43  servesCocktails               2035 non-null   float64
 44  servesDessert                 2428 non-null   float64
 45  servesCoffee                  2573 non-null   float64
 46  goodForChildren               2214 non-null   float64
 47  allowsDogs                    1481 non-null   float64
 48  restroom                      3003 non-null   float64
 49  goodForGroups                 1847 non-null   float64
 50  goodForWatchingSports         3126 non-null   float64
 51  paymentOptions                4206 non-null   object
 52  parkingOptions                1987 non-null   object
 53  accessibilityOptions          2851 non-null   object
 54  addressDescriptor             4392 non-null   object
 55  googleMapsLinks               4392 non-null   object
 56  priceRange                    3090 non-null   object
 57  timeZone                      4392 non-null   object
 58  postalAddress                 4386 non-null   object
 59  googleMapsTypeLabel           4392 non-null   object
 60  curbsidePickup                1205 non-null   float64
 61  containingPlaces              745 non-null    object
 62  editorialSummary              344 non-null    object
 63  fuelOptions                   43 non-null     object
 64  servesVegetarianFood          1497 non-null   float64
 65  consumerAlert                 2 non-null      object
dtypes: float64(25), int64(1), object(26), str(14)
memory usage: 4.7+ MB

In [4]:
cph_df.describe()

,rating,utcOffsetMinutes,userRatingCount,takeout,delivery,dineIn,reservable,servesBreakfast,servesLunch,servesDinner,servesBeer,servesWine,servesBrunch,outdoorSeating,liveMusic,menuForChildren,servesCocktails,servesDessert,servesCoffee,goodForChildren,allowsDogs,restroom,goodForGroups,goodForWatchingSports,curbsidePickup,servesVegetarianFood
count,4046.000000,4392.0,4046.000000,3237.000000,2968.000000,3910.000000,2367.000000,1732.000000,3009.000000,3249.000000,2754.000000,2451.000000,1713.000000,2187.000000,3465.000000,2044.000000,2035.000000,2428.000000,2573.000000,2214.000000,1481.000000,3003.000000,1847.000000,3126.000000,1205.000000,1497.000000
mean,4.197257,60.0,398.480969,0.914427,0.448787,0.993350,0.820870,0.368938,0.969757,0.978763,0.740015,0.722154,0.308815,0.718793,0.043001,0.692270,0.515971,0.871911,0.833657,0.803975,0.160702,0.876457,0.965891,0.014395,0.351037,0.981296
std,0.548070,0.0,869.449306,0.279776,0.497454,0.081284,0.383542,0.482656,0.171283,0.144197,0.438706,0.448028,0.462140,0.449691,0.202890,0.461667,0.499868,0.334258,0.372460,0.397078,0.367380,0.329114,0.181559,0.119133,0.477493,0.135523
min,1.000000,60.0,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,60.0,52.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
50%,4.300000,60.0,161.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000
75%,4.600000,60.0,435.750000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,5.000000,60.0,25668.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [5]:
import json
from collections import Counter

with open((GOOGLE_MAPS_DATASETS / "copenhagen-bounds-limit10_20260316_125502.json"), "r", encoding="utf-8") as f:
    data = json.load(f)
# Extract locality from addressComponents
localities = []
for place in data:
    address_components = place.get("addressComponents", [])
    for component in address_components:
        if "locality" in component.get("types", []):
            localities.append(component["longText"])
            break

# Count and display
counter = Counter(localities)
for municipality, count in counter.most_common():
    print(f"{municipality}: {count}")

København: 2743
Frederiksberg: 331
Kongens Lyngby: 114
Kastrup: 97
Hvidovre: 87
Rødovre: 79
Taastrup: 75
Hellerup: 70
Greve: 62
Ballerup: 60
Charlottenlund: 60
Søborg: 54
Herlev: 49
Glostrup: 48
Klampenborg: 47
Gentofte: 41
Albertslund: 37
Ishøj: 37
Bagsværd: 30
Brøndby: 29
Dragør: 25
Værløse: 23
Farum: 23
Virum: 22
Holte: 21
Vallensbæk Strand: 17
Copenhagen: 16
Brøndby Strand: 13
Skovlunde: 10
Karlslunde: 10
Dyssegård: 9
Måløv: 8
Smørum: 6
Nærum: 6
Stenløse: 4
Vallensbæk: 3
Veksø: 2
Hovedstaden: 2
København K: 2
Amager: 2
Slangerup: 1
Veksø Sjælland: 1
Skodsborg: 1
Kgs Lyngby: 1
Skovshoved: 1
kbh k: 1
kl: 1
søsiden: 1
Solrød Strand: 1
Sundbyøster: 1
Fields: 1

In [6]:
cols_to_keep = [
    "name", 
    "id", 
    "types", 
    "formattedAddress", 
    "location", 
    "rating", 
    "googleMapsUri",
    "websiteUri",
    "businessStatus",
    "priceLevel",
    "displayName",
    "takeout",
    "delivery",
    "dineIn",
    "servesBreakfast",
    "servesLunch",
    "servesDinner",
    "servesBrunch",
    "servesDessert",
    "primaryType",
    "primaryTypeDisplayName",
    "reviews",
    "priceRange",
    "postalAddress",
    "editorialSummary",
    "servesVegetarianFood",
]

len(cols_to_keep)

26

In [7]:
cph_df = cph_df[cols_to_keep]
cph_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4392 entries, 0 to 4391
Data columns (total 26 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   name                    4392 non-null   str
 1   id                      4392 non-null   str
 2   types                   4392 non-null   object
 3   formattedAddress        4392 non-null   str
 4   location                4392 non-null   object
 5   rating                  4046 non-null   float64
 6   googleMapsUri           4392 non-null   str
 7   websiteUri              3600 non-null   str
 8   businessStatus          4392 non-null   str
 9   priceLevel              1738 non-null   str
 10  displayName             4392 non-null   object
 11  takeout                 3237 non-null   float64
 12  delivery                2968 non-null   float64
 13  dineIn                  3910 non-null   float64
 14  servesBreakfast         1732 non-null   float64
 15  servesLunch             3009 non-null   float64
 16  servesDinner            3249 non-null   float64
 17  servesBrunch            1713 non-null   float64
 18  servesDessert           2428 non-null   float64
 19  primaryType             4387 non-null   str
 20  primaryTypeDisplayName  4387 non-null   object
 21  reviews                 4046 non-null   object
 22  priceRange              3090 non-null   object
 23  postalAddress           4386 non-null   object
 24  editorialSummary        344 non-null    object
 25  servesVegetarianFood    1497 non-null   float64
dtypes: float64(10), object(8), str(8)
memory usage: 2.1+ MB

In [8]:
cph_df.describe()

,rating,takeout,delivery,dineIn,servesBreakfast,servesLunch,servesDinner,servesBrunch,servesDessert,servesVegetarianFood
count,4046.000000,3237.000000,2968.000000,3910.000000,1732.000000,3009.000000,3249.000000,1713.000000,2428.000000,1497.000000
mean,4.197257,0.914427,0.448787,0.993350,0.368938,0.969757,0.978763,0.308815,0.871911,0.981296
std,0.548070,0.279776,0.497454,0.081284,0.482656,0.171283,0.144197,0.462140,0.334258,0.135523
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,4.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
50%,4.300000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000
75%,4.600000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
mini_box = pd.read_json(GOOGLE_MAPS_DATASETS / 'mini-box_20260311_101610.json')
mini_box.info()

<class 'pandas.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 64 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   name                          31 non-null     str
 1   id                            31 non-null     str
 2   types                         31 non-null     object
 3   formattedAddress              31 non-null     str
 4   addressComponents             31 non-null     object
 5   plusCode                      31 non-null     object
 6   location                      31 non-null     object
 7   viewport                      31 non-null     object
 8   rating                        29 non-null     float64
 9   googleMapsUri                 31 non-null     str
 10  websiteUri                    25 non-null     str
 11  regularOpeningHours           28 non-null     object
 12  utcOffsetMinutes              31 non-null     int64
 13  adrFormatAddress              31 non-null     str
 14  businessStatus                31 non-null     str
 15  priceLevel                    18 non-null     str
 16  userRatingCount               29 non-null     float64
 17  iconMaskBaseUri               31 non-null     str
 18  iconBackgroundColor           31 non-null     str
 19  displayName                   31 non-null     object
 20  primaryTypeDisplayName        31 non-null     object
 21  takeout                       27 non-null     float64
 22  dineIn                        31 non-null     bool
 23  curbsidePickup                6 non-null      float64
 24  reservable                    18 non-null     float64
 25  servesBreakfast               14 non-null     float64
 26  servesLunch                   24 non-null     float64
 27  servesDinner                  27 non-null     float64
 28  servesBeer                    22 non-null     float64
 29  servesBrunch                  15 non-null     float64
 30  servesVegetarianFood          12 non-null     float64
 31  currentOpeningHours           28 non-null     object
 32  primaryType                   31 non-null     str
 33  shortFormattedAddress         31 non-null     str
 34  reviews                       28 non-null     object
 35  photos                        27 non-null     object
 36  outdoorSeating                20 non-null     float64
 37  liveMusic                     30 non-null     float64
 38  menuForChildren               18 non-null     float64
 39  servesCocktails               18 non-null     float64
 40  servesDessert                 21 non-null     float64
 41  servesCoffee                  17 non-null     float64
 42  allowsDogs                    13 non-null     float64
 43  restroom                      23 non-null     float64
 44  goodForWatchingSports         24 non-null     float64
 45  paymentOptions                31 non-null     object
 46  accessibilityOptions          24 non-null     object
 47  addressDescriptor             31 non-null     object
 48  googleMapsLinks               31 non-null     object
 49  priceRange                    23 non-null     object
 50  timeZone                      31 non-null     object
 51  postalAddress                 31 non-null     object
 52  googleMapsTypeLabel           31 non-null     object
 53  nationalPhoneNumber           26 non-null     str
 54  internationalPhoneNumber      26 non-null     str
 55  delivery                      22 non-null     float64
 56  servesWine                    21 non-null     float64
 57  goodForChildren               19 non-null     float64
 58  parkingOptions                11 non-null     object
 59  currentSecondaryOpeningHours  5 non-null      object
 60  regularSecondaryOpeningHours  5 non-null      object
 61  goodForGroups                 14 non-null     float64
 62  editorialSummary              3 non-null      object
 63  containingPlaces              1 non-null      object
dtypes: bool(1), float64(24), int64(1), object(24), str(14)
memory usage: 33.2+ KB

In [10]:
noma = cph_df[cph_df['displayName'].apply(lambda x: x['text'] == "Mad & Kaffe")]

# import pandas as pd
# pd.set_option('display.max_colwidth', None)
# print(noma['priceRange'])

[name], 	[places/ChIJpYCQZztTUkYRFOE368Xs6kI],
[id], 	[ChIJpYCQZztTUkYRFOE368Xs6kI],
[types], 	[[scandinavian_restaurant, fine_dining_restaura...],
[formattedAddress], 	[Refshalevej 96, 1432 Indre By, Denmark],
[location], 	[{'latitude': 55.6828273, 'longitude': 12.6104808}],
[rating], 	[4.6],
[googleMapsUri], 	[https://maps.google.com/?cid=48219266858525575...],
[websiteUri], 	[https://noma.dk/],
[businessStatus], 	[CLOSED_TEMPORARILY],
[priceLevel], 	[PRICE_LEVEL_VERY_EXPENSIVE],
[displayName], 	[{'text': 'Noma', 'languageCode': 'en'}],
[takeout], 	[0.0],
[delivery], 	[0.0],
[dineIn], 	[1.0],
[servesBreakfast], 	[0.0],
[servesLunch], 	[1.0],
[servesDinner], 	[1.0],
[servesBrunch], 	[0.0],
[servesDessert], 	[1.0],
[primaryType], 	[scandinavian_restaurant],
[primaryTypeDisplayName], 	[{'text': 'Scandinavian Restaurant', 'languageC...],
[reviews], 	[[{'name': 'places/ChIJpYCQZztTUkYRFOE368Xs6kI/...],
[priceRange], 	[{'startPrice': {'currencyCode': 'DKK', 'units'...],
[postalAddress], 	[{'regionCode': 'DK', 'languageCode': 'en-US', ...],
[editorialSummary], 	[{'text': 'Chef Rene Redzepi's gastronomic mecc...],
[servesVegetarianFood], 	[1.0],

In [11]:
noma.T

,2615,4177
name,places/ChIJAcjGaXZTUkYRXFFcKCkRt0c,places/ChIJjYGh-kxTUkYRuO65MpgG4eA
id,ChIJAcjGaXZTUkYRXFFcKCkRt0c,ChIJjYGh-kxTUkYRuO65MpgG4eA
types,"[cafe, brunch_restaurant, breakfast_restaurant...","[cafe, brunch_restaurant, coffee_shop, breakfa..."
formattedAddress,"Sønder Blvd. 68, 1720 Vesterbro, Denmark","Tyrolsgade 6, 2300 Amager Øst, Denmark"
location,"{'latitude': 55.6659376, 'longitude': 12.5503967}","{'latitude': 55.659096299999995, 'longitude': ..."
rating,4.5,4.4
googleMapsUri,https://maps.google.com/?cid=51676179658994036...,https://maps.google.com/?cid=16204240185011596...
websiteUri,http://www.madogkaffe.dk/,http://www.madogkaffe.dk/
businessStatus,OPERATIONAL,OPERATIONAL
priceLevel,PRICE_LEVEL_MODERATE,PRICE_LEVEL_MODERATE
displayName,"{'text': 'Mad & Kaffe', 'languageCode': 'en'}","{'text': 'Mad & Kaffe', 'languageCode': 'en'}"
takeout,1.0,1.0
delivery,0.0,0.0
dineIn,1.0,1.0
servesBreakfast,1.0,1.0
servesLunch,1.0,1.0
servesDinner,1.0,1.0
servesBrunch,1.0,1.0
servesDessert,1.0,1.0
primaryType,cafe,cafe
primaryTypeDisplayName,"{'text': 'Cafe', 'languageCode': 'en-US'}","{'text': 'Cafe', 'languageCode': 'en-US'}"
reviews,[{'name': 'places/ChIJAcjGaXZTUkYRXFFcKCkRt0c/...,[{'name': 'places/ChIJjYGh-kxTUkYRuO65MpgG4eA/...
priceRange,"{'startPrice': {'currencyCode': 'DKK', 'units'...","{'startPrice': {'currencyCode': 'DKK', 'units'..."
postalAddress,"{'regionCode': 'DK', 'languageCode': 'en-US', ...","{'regionCode': 'DK', 'languageCode': 'en-US', ..."
editorialSummary,NaN,NaN
servesVegetarianFood,1.0,1.0